Session logger
oxen-io/websites pull request #19
Opened 2024-07-14 23:55 UTC by Aerilym

2024-07-23 00:44 UTC, yougotwill requested changes
Nice work but couple of discussion points

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +/* eslint-disable  @typescript-eslint/no-explicit-any */
Naughty naughty. Also if you really want to do this then add it to timedLog.ts as well please

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +   * timedLog.info('A message was sent after {time} with id 7');
Very cool!

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +   * @example Saving the Timed Log
Very nice examples! I was going to suggest adding a readme so it's easier to know how to use the logger package but now I request we get @examples on the logger class with some example calls instead please? 😄🙏

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +   * Create a new {@link TimedLog} instance. This can be called later to log a message with an elapsed time.
Can you update this description to indicate what it does differently to the method above. Got confused and thought it was duplicate code at first glance

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +  public initTimedLogWithInitialLog(
Naming here is a big namey. What do you think about using startMessage instead of initalLogMessage?

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +        `Creating a new timed log with the same label as an existing timed log would cause the existing log event to be written over. The first call of timeEnd with the same label will consume this s
🫠

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +        `Creating a new timed log with the same label as an existing timed log would cause the existing log event to be written over. The first call of timeEnd with the same label will consume this s
Think this needs an @ example please

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +   * @deprecated use {@link initTimedLog} for proper timed logs using {@link TimedLog}
How have you deprecated things when this package isn't even public yet. Surely we can refactor and remove haha?

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +        `Creating a new timed log with the same label as an existing timed log would cause the existing log event to be written over. The first call of timeEnd with the same label will consume this s
Think you need to make an error's file or something and import the strings into the warnings here? These files are already pretty long to read. Thoughts?

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +   * @deprecated use {@link initTimedLog} for proper timed logs using {@link TimedLog}
same comment as `time`

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +   * @param timedLog The {@link TimedLog} instance
What is "stale"?

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/logger.ts
> +   * This calls {@link handleStaleTimedLog} on each stale log.
```suggestion
   * Handle stale log checking for all logs in {@link activeTimedLogs}.
```

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/timedLog.ts
> +  constructor(logger: Logger, initialLogMessage?: string, initialLogMessageLevel?: keyof Logger) {
Just thinking we could make this an object like 

```ts
initialLogMessage: {
  message: string,
  level: string,
}
```

Can't remember if you have already got a type that pairs a message and a log level but you could use it here instead?

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/timedLog.ts
> +   * timedLog.debug('A message was sent with id 8');
So the id also gets incremented each time we reset?

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/timedLog.ts
> +  public static formatDistanceToNow(time: number) {
haha the legendary distance has returned!

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/timedLog.ts
> +    function formatMillisecondsToSeconds(milliseconds: number): string {
Maybe move this outside of the class (if that works) instead of it getting redeclared every time this function is called?

2024-07-23 00:44 UTC, yougotwill commented on packages/logger/timedLog.ts
> +export class TimedLog {
Do we not want this to inherit from the `SessionLogger` some what? Thinking specifically about the log functions: warn, error, log, etc.

2024-07-23 03:42 UTC, Aerilym commented on apps/staking/package.json
> +    "pino": "^9.2.0",
Yeah this is is why it was hard to get this working on nextjs clientside, you do require it because next needs to transpile it

2024-07-23 03:45 UTC, Aerilym commented on packages/logger/logger.ts
> +/* eslint-disable  @typescript-eslint/no-explicit-any */
Yeah it needs this because the official type for a console log is (..args:any[]). adding it to the other file

2024-07-23 03:46 UTC, Aerilym commented on packages/logger/timedLog.ts
> +export class TimedLog {
we dont, this is a logger agnostic function, it takes the logger in the constructor. So you can give it `SessionLogger` (which in turn takes a logger like `console.log` or `pino.log`)

2024-07-23 03:46 UTC, Aerilym commented on packages/logger/timedLog.ts
> +export class TimedLog {
Even tho this has log levels too it uses an abstracted `log` method which does the time printing

2024-07-23 03:48 UTC, Aerilym commented on packages/logger/timedLog.ts
> +  constructor(logger: Logger, initialLogMessage?: string, initialLogMessageLevel?: keyof Logger) {
Yeah good idea, ive made the change

2024-07-23 03:49 UTC, Aerilym commented on packages/logger/timedLog.ts
> +   * timedLog.debug('A message was sent with id 8');
The id here is part of the usage example, in the string you give it

2024-07-23 03:50 UTC, Aerilym commented on packages/logger/timedLog.ts
> +    function formatMillisecondsToSeconds(milliseconds: number): string {
Missed this, moved outside

2024-07-23 03:55 UTC, Aerilym commented on packages/logger/logger.ts
> +   * @example Saving the Timed Log
Yeah ill add this when i have some proper examples and write the docs for all the packages

2024-07-23 04:01 UTC, Aerilym commented on packages/logger/logger.ts
> +   * Create a new {@link TimedLog} instance. This can be called later to log a message with an elapsed time.
I'll do you one better, I've merged there usage based on the timedLog changes

2024-07-23 04:01 UTC, Aerilym commented on packages/logger/logger.ts
> +  public initTimedLogWithInitialLog(
I'll do you one better, I've merged there usage based on the timedLog changes

2024-07-23 04:02 UTC, Aerilym commented on packages/logger/logger.ts
> +   * @deprecated use {@link initTimedLog} for proper timed logs using {@link TimedLog}
I've actually deprecated `console.time`. This wraps around an existing logger, so if you wrap this around `console.log` and you're using `console.time`, we want people to use our better method :)

2024-07-23 04:03 UTC, Aerilym commented on packages/logger/logger.ts
> +        `Creating a new timed log with the same label as an existing timed log would cause the existing log event to be written over. The first call of timeEnd with the same label will consume this s
Ah these are only used by the deprecated method to support using the `console.time` pattern with our far superior `timedLog` I will mark these as deprecated too

2024-07-23 04:07 UTC, Aerilym commented on packages/logger/logger.ts
> +   * @deprecated use {@link initTimedLog} for proper timed logs using {@link TimedLog}
See time comment :)

2024-07-23 04:07 UTC, Aerilym commented on packages/logger/logger.ts
> +   * @param timedLog The {@link TimedLog} instance
as in older than the staleTime

2024-07-23 04:09 UTC, Aerilym commented on packages/logger/logger.ts
> +        `Creating a new timed log with the same label as an existing timed log would cause the existing log event to be written over. The first call of timeEnd with the same label will consume this s
I mean seems overkill for a few warnings and all of them are different

2024-07-23 04:11 UTC, Aerilym commented on packages/util/logger.ts
> +import { LOG_LEVEL, SessionLogger, type SessionLoggerOptions } from '@session/logger';
fixed

2024-07-23 04:12 UTC, Aerilym commented on packages/util/logger.ts
> +    constructLoggingArgs: (...data: Array<any>) => {
its gotta be any as thats the node js type, but i agree, everything should be `Array<any>`

2024-07-25 23:28 UTC, yougotwill requested changes

2024-07-25 23:28 UTC, yougotwill commented on apps/staking/package.json
> +    "pino": "^9.2.0",
Strange but alright for now👍

2024-07-25 23:28 UTC, yougotwill commented on packages/logger/logger.ts
> +   * @param timedLog The {@link TimedLog} instance
Bruh.

2024-07-25 23:28 UTC, yougotwill commented on packages/logger/timedLog.ts
> +export class TimedLog {
fine

2024-07-25 23:28 UTC, yougotwill commented on packages/logger/timedLog.ts
> +   * timedLog.debug('A message was sent with id 8');
Ah okay cool.

2024-07-25 23:29 UTC, yougotwill commented on packages/util/logger.ts
> +    constructLoggingArgs: (...data: Array<any>) => {
Cool

2024-07-25 23:34 UTC, yougotwill commented on packages/logger/logger.ts
> +   * @param timedLog The {@link TimedLog} instance
Noice

2024-07-25 23:34 UTC, yougotwill approved these changes
LGTM 🚢

2024-07-25 23:38 UTC, merged