Node Registration and TOS
oxen-io/websites pull request #21
Opened 2024-07-16 08:09 UTC by Aerilym

2024-07-18 03:56 UTC, yougotwill requested changes

2024-07-18 03:56 UTC, yougotwill commented on apps/staking/app/stake/[nodeId]/BlockExplorerLink.tsx
```suggestion
  }, [data, nodeId]);
```

deps array

2024-07-18 03:56 UTC, yougotwill commented on apps/staking/app/stake/PendingNodesModule.tsx
> +  /** NOTE: The parent div needs to be rendered while loading in case nodes are returned, this
Nice comment!

2024-07-18 03:56 UTC, yougotwill commented on apps/staking/app/page.tsx
> +const PrimaryButton = ({ size, className }: { size: 'sm' | 'lg'; className?: string }) => {
Should we not have a `button.tsx`?

2024-07-18 03:56 UTC, yougotwill commented on apps/staking/app/page.tsx
> +    <Link href={LANDING_BUTTON_URL.PRIMARY} prefetch className={className}>
aria label?

2024-07-18 03:56 UTC, yougotwill commented on apps/staking/app/page.tsx
> +    <Link href={LANDING_BUTTON_URL.SECONDARY} target="_blank" prefetch className={className}>
aria label

2024-07-18 03:56 UTC, yougotwill commented on apps/staking/app/mystakes/modules/BalanceModule.tsx
>    );
```suggestion
    { enabled: !!address }
```

2024-07-18 03:56 UTC, yougotwill commented on apps/staking/app/mystakes/modules/DailyNodeReward.tsx
> +        ~{data}
Not a typo?

2024-07-18 06:40 UTC, Aerilym commented on packages/contracts/scripts/generate-abis.ts
> +    execSync(`cd ${destinationPath} && git switch integration`);
just using the integration branch of the contracts as its most up to date, will be overhauling all of this when we build our testing library better

2024-07-18 06:41 UTC, Aerilym commented on apps/staking/lib/queries/getPendingNodes.ts
> +  if (registrationsResponse.data.registrations.length && stakedNodesResponse.data.nodes.length) {
If we have both we can process the list, otherwise we just return the registrationsResponse. We only process based on stakeNodesResponse, so if both dont exist we do no processing

2024-07-18 06:43 UTC, Aerilym commented on apps/staking/components/NodeCard.tsx
> +      // TODO - add contributor list sorting
when we do the multicontributor feature development

2024-07-18 06:49 UTC, Aerilym commented on packages/ui/package.json
> +    "@uidotdev/usehooks": "^2.4.1",
Discussed, but no real reason, went with this because its small

2024-07-18 06:52 UTC, Aerilym commented on apps/staking/app/stake/page.tsx
> +            referrerPolicy="no-referrer"
Pretty neat: https://chromestatus.com/feature/6140064063029248
as of 2021: All current versions of major browsers now automatically use the behavior of rel="noopener" for any target="_blank" link

2024-07-18 06:57 UTC, Aerilym commented on apps/staking/app/page.tsx
> +const PrimaryButton = ({ size, className }: { size: 'sm' | 'lg'; className?: string }) => {
Not sure what you mean, this is where Button comes from

2024-07-18 06:57 UTC, Aerilym commented on apps/staking/app/page.tsx
> +    <Link href={LANDING_BUTTON_URL.PRIMARY} prefetch className={className}>
Links dont need aria labels if they have visible text on the screen

2024-07-18 06:57 UTC, Aerilym commented on apps/staking/app/page.tsx
> +    <Link href={LANDING_BUTTON_URL.SECONDARY} target="_blank" prefetch className={className}>
Links dont need aria labels if they have visible text on the screen

2024-07-18 06:58 UTC, Aerilym commented on packages/contracts/hooks/ServiceNodeRewards.tsx
> +    functionName: 'addBLSPublicKey',
Happy to chat through this so we can get on the same page

2024-07-18 07:00 UTC, Aerilym commented on packages/util/string.ts
> +  if (!str1 || !str2 || str1.length < 3 || str1.length !== str2.length) return false;
fixed in next pr (about to be merged)

2024-07-18 07:07 UTC, Aerilym commented on apps/staking/components/TOSHandler.tsx
> +          You must accept the{' '}
Legal copy, but by the time we localise we probs wont have this

2024-07-18 07:07 UTC, Aerilym commented on apps/staking/components/TOSHandler.tsx
> +            . Please read these Terms carefully. If you do not agree to these Terms, you must not
idk `. Please` is pretty clear?

2024-07-18 07:19 UTC, yougotwill commented on apps/staking/components/TOSHandler.tsx
> +            . Please read these Terms carefully. If you do not agree to these Terms, you must not
All good

2024-07-18 07:19 UTC, yougotwill commented on apps/staking/app/stake/page.tsx
> +            referrerPolicy="no-referrer"
TIL!

2024-07-18 07:20 UTC, yougotwill commented on apps/staking/app/page.tsx
> +const PrimaryButton = ({ size, className }: { size: 'sm' | 'lg'; className?: string }) => {
I mean moving the Primary and Secondary buttons to a buttons.tsx file within the staking app repo

2024-07-18 07:22 UTC, Aerilym commented on apps/staking/app/page.tsx
> +const PrimaryButton = ({ size, className }: { size: 'sm' | 'lg'; className?: string }) => {
well its just the landing page primary and secondary

2024-07-18 07:23 UTC, Aerilym commented on apps/staking/app/mystakes/modules/DailyNodeReward.tsx
> +        ~{data}
correct

2024-07-18 07:23 UTC, Aerilym commented on packages/contracts/abis/TokenVestingStaking.ts
> +    type: 'function',
it is

2024-07-19 00:36 UTC, Aerilym commented on apps/staking/app/stake/[nodeId]/register/NodeRegistration.tsx
> +  const nodeRunning = Boolean(runningNode && 'state' in runningNode && runningNode.state);
`'state' in runningNode` will only return true if the object contains that key, `runningNode.state` will return if the value is truthy. This will hopefully be replaced once we have a better way of doing this

2024-07-19 00:41 UTC, Aerilym commented on apps/staking/app/stake/[nodeId]/register/NodeRegistration.tsx
> +  stakeAmount,
this is fine, will be used later (see todo)

2024-07-19 00:42 UTC, Aerilym commented on apps/staking/app/stake/[nodeId]/register/NodeRegistration.tsx
> +  return `${stageDictionaryMap[stage]}.${stage > currentStage || subStage === 'idle' ? 'pending' : subStage}`;
:mage:

2024-07-19 00:58 UTC, yougotwill commented on apps/staking/app/stake/[nodeId]/register/NodeRegistration.tsx
> +  const nodeRunning = Boolean(runningNode && 'state' in runningNode && runningNode.state);
Cool cool. Resolved

2024-07-19 00:58 UTC, yougotwill commented on apps/staking/app/page.tsx
> +const PrimaryButton = ({ size, className }: { size: 'sm' | 'lg'; className?: string }) => {
fine for now. If the buttons get reused you know what to do 😉

2024-07-19 01:09 UTC, yougotwill approved these changes
LGTM 🚢

2024-07-19 01:42 UTC, merged