Add checking stake approval before requesting approval to skip approval
oxen-io/websites pull request #25
Opened 2024-07-22 07:41 UTC by Aerilym

2024-07-22 23:48 UTC, yougotwill requested changes
left some comments

2024-07-22 23:48 UTC, yougotwill commented on packages/contracts/hooks/SENT.tsx
> +  allowance: ReadContractData<typeof SENTAbi, 'allowance', [Address, Address]>;
How is the contract read here separate to the getAllowance function?

2024-07-22 23:48 UTC, yougotwill commented on packages/contracts/hooks/SENT.tsx
> +    chainId: chains[CHAIN.TESTNET].id,
Should we not start having a env flag or global variable for the chain we want to use? That way down the line it's a one line switch from testnet to mainet?

2024-07-22 23:48 UTC, yougotwill commented on packages/contracts/hooks/SENT.tsx
> +      if (!isProduction()) {
If production it's okay to allow this?

2024-07-22 23:48 UTC, yougotwill commented on packages/contracts/hooks/SENT.tsx
> +
I prefer new lines between if statement blocks. You can do one or the other please 🤷

2024-07-22 23:48 UTC, yougotwill commented on packages/contracts/hooks/contract-hooks.tsx
> +  chainId: number;
Can we not inherit from `ContractWriteQueryFetchOptions` here?

2024-07-22 23:51 UTC, Aerilym commented on packages/contracts/hooks/contract-hooks.tsx
> +  chainId: number;
I dont want to pollute the read query options as we'll likely add more props to the write query than just chainId, so we want them to be separate as they're unrelated. I have plans to split this file into two when i get time

2024-07-22 23:53 UTC, Aerilym commented on packages/contracts/hooks/SENT.tsx
> +  allowance: ReadContractData<typeof SENTAbi, 'allowance', [Address, Address]>;
I'm not sure i follow. `getAllowance()` triggers the getting of the allowance (the query), and allowance is the allowance value (which changes based on the query)

2024-07-22 23:53 UTC, Aerilym commented on packages/contracts/hooks/SENT.tsx
> +    chainId: chains[CHAIN.TESTNET].id,
We're going to build a network management system as we need to pass this through depending on the network and so the chain you're on. You can switch chain at any time. its hard coded here as we dont have that built yet

2024-07-22 23:54 UTC, Aerilym commented on packages/contracts/hooks/SENT.tsx
> +      if (!isProduction()) {
if not production :)

2024-07-22 23:54 UTC, Aerilym commented on packages/contracts/hooks/SENT.tsx
> +
Ah this was missed. fixed

2024-07-23 00:55 UTC, Aerilym commented on packages/contracts/hooks/SENT.tsx
> +  allowance: ReadContractData<typeof SENTAbi, 'allowance', [Address, Address]>;
So this is the query convention for tanstack query :)

2024-07-23 00:55 UTC, merged