Optimise and fix write contract hooks
oxen-io/websites pull request #27
Opened 2024-07-30 02:06 UTC by Aerilym

2024-07-31 00:14 UTC, yougotwill requested changes
Nice work but couple things to sort out

2024-07-31 00:14 UTC, yougotwill commented on packages/contracts/hooks/useContractWriteQuery.tsx
> +  };
Very nice work dude

2024-07-31 00:14 UTC, yougotwill commented on packages/contracts/hooks/ServiceNodeRewards.tsx
> +import { type ContractWriteQueryProps, useContractWriteQuery } from './useContractWriteQuery';
`ContractWriteQueryProps` defined but not used

2024-07-31 00:14 UTC, yougotwill commented on packages/contracts/hooks/ServiceNodeRewards.tsx
>  export type ClaimRewardsQuery = WriteContractQuery & {
`WriteContractQuery` not defined

2024-07-31 00:14 UTC, yougotwill commented on packages/contracts/hooks/ServiceNodeRewards.tsx
>  export type ClaimRewardsQuery = WriteContractQuery & {
I can't reach it on GitHub but there is the same lint error on line 21, 55. Actually this entire file seems to have lint errors in various places 😅

```tsx
Argument of type '{ contract: "ServiceNodeRewards"; functionName: "claimRewards"; }' is not assignable to parameter of type '{ contract: "ServiceNodeRewards"; defaultArgs?: readonly [] | undefined; functionName: "claimRewards"; } & ContractWriteQueryFetchOptions'.
  Property 'chain' is missing in type '{ contract: "ServiceNodeRewards"; functionName: "claimRewards"; }' but required in type 'ContractWriteQueryFetchOptions'.
  ```

2024-07-31 00:14 UTC, yougotwill commented on packages/contracts/hooks/SENT.tsx
> +export const formatSENTBigInt = (value?: bigint, decimals?: number, hideSymbol?: boolean) =>
Do these need to be exported if they are not used anywhere else?

2024-07-31 23:13 UTC, Aerilym commented on packages/contracts/hooks/SENT.tsx
> +export const formatSENTBigInt = (value?: bigint, decimals?: number, hideSymbol?: boolean) =>
They're used in the claim rewards PR, changes all over the site

2024-07-31 23:14 UTC, Aerilym commented on packages/contracts/hooks/ServiceNodeRewards.tsx
> +import { type ContractWriteQueryProps, useContractWriteQuery } from './useContractWriteQuery';
used in rewards claim, had to include it here because on my local changes i have all the rewards claim stuff, too much work to separate

2024-07-31 23:14 UTC, Aerilym commented on packages/contracts/hooks/ServiceNodeRewards.tsx
>  export type ClaimRewardsQuery = WriteContractQuery & {
should be fixed now?

2024-07-31 23:17 UTC, Aerilym commented on packages/contracts/hooks/useContractWriteQuery.tsx
> +  defaultArgs?: Args;
The order doesnt matter as its an object, ts will complain if an optional arg comes before a required arg in a function eg:
```ts
function firePotatoCannon(direction: string, power?: number, colour: string){
  //...
}

```
If fact as I write this webstorm warns me: `A required parameter cannot follow an optional parameter`

2024-07-31 23:19 UTC, Aerilym commented on packages/contracts/hooks/useEstimateContractFee.tsx
> +    if (gasAmountEstimate !== null) return 'success';
it is, its about the state of the request, we dont care about what the value is for the status, we only care that is is not null.

Any error logic would be handles elsewhere, if we are concerned about `0` or `negative`, in the `estimateGasAmount()` function we'd have:
```ts
 if (gas <= 0){
  setError('Gas estimate can\'t be zero or negative`);
}
```

Then the status will be error as the `error` object is defined

2024-08-01 01:58 UTC, yougotwill approved these changes
LGTM 🚢

2024-08-01 01:58 UTC, yougotwill commented on packages/contracts/hooks/useEstimateContractFee.tsx
> +    if (gasAmountEstimate !== null) return 'success';
Okay cool 👍

2024-08-01 01:58 UTC, yougotwill commented on packages/contracts/hooks/ServiceNodeRewards.tsx
> +import { type ContractWriteQueryProps, useContractWriteQuery } from './useContractWriteQuery';
It is now used.

2024-08-01 05:08 UTC, merged