chore: create issue templates
oxen-io/websites pull request #33
Opened 2024-08-12 09:24 UTC by Aerilym

2024-08-13 05:05 UTC, yougotwill requested changes
For these you can use session-ios for inspiration they are pretty good templates.

https://github.com/oxen-io/session-ios/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml
https://github.com/oxen-io/session-ios/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml

2024-08-13 05:05 UTC, yougotwill commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots and recordings to help explain your problem.
You could suggest some tools to use for recording for different platforms?

2024-08-13 05:05 UTC, yougotwill commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Wallet App: [Metamask, Brave, Ledger]
Maybe specify how it was connected. WalletConnect vs the app's native connection?

2024-08-13 08:05 UTC, Aerilym commented on .github/ISSUE_TEMPLATE/bug_report.md
> +If applicable, add screenshots and recordings to help explain your problem.
native recording should work fine, dont need high res or high fps

2024-08-14 00:07 UTC, yougotwill requested changes
Nice work

2024-08-14 00:07 UTC, yougotwill commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
Link explaining how to save logs? https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-console-file

I'm actually thinking it might be good to get marketing to setup some zendesk content around saving logs and screenshots / screen recording? 🤔

2024-08-14 00:07 UTC, yougotwill commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
There is this entry https://sessionapp.zendesk.com/hc/en-us/articles/4439260416665-How-can-I-report-a-bug-or-issue but it's session specific

2024-08-14 00:10 UTC, Aerilym commented on .github/ISSUE_TEMPLATE/config.yml
> +blank_issues_enabled: true
vs code is having a stroke, the `ISSUE_TEMPLATE/config.yml` can only contain `blank_issues_enabled` and `contact_links`, see: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

2024-08-14 00:12 UTC, Aerilym commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
Oh cool, i was just having this here for when i end up doing proper logging but this is great

2024-08-14 00:44 UTC, yougotwill approved these changes
LGTM 🚢

2024-08-14 00:44 UTC, yougotwill commented on .github/ISSUE_TEMPLATE/config.yml
> +blank_issues_enabled: true
Yup confirmed it's fine. Strange that. Resolved

2024-08-14 00:45 UTC, merged