Session staking web app part 1
oxen-io/websites pull request #4
Opened 2024-05-28 05:50 UTC by Aerilym

# Session Staking Web App Part 1

Initial setup for the Session Token staking web app.

## Changes

### New Features

- Created the initial structure for the Session Token staking web app.
- Created initial staked nodes page and associated components.
- Created utility pages (loading and 404)
- Created Stake Modules.
- Integrated form components from shadcn for better UI consistency.
- Upgraded wagmi and viem libraries.
- Created a button to make server-side token adding transactions.
- Created a test faucet for distributing Session Token tokens.
-  Added a dropdown menu component from shadcn.
- Created a Chain Banner for Unsupported Chains to inform users if they're on an unsupported or unavailable chain.
- Created a dropdown for changing networks.
- Added ability to change testnet chains in the faucet.
- Configured Tailwind suggestions regex in settings.
- Included new strings in the dictionary for localization.
- Updated Tailwind configuration to include new screen heights.
- Added tooltips in the UI library.
- Added new icons to the UI library.
- Rewrote the logic for the staked node card UI.
- Created a screen container component for better layout management.
- Extracted the localized provider to add default values for localization.

### Fixes and Improvements

- Add `@session/contracts` to the list of Next.js transpile packages.
- Adjusted code to handle zero ETH balance scenarios.
- Updated locale string for ETH minimum balance.
- Updated the link to the Arbitrum Sepolia faucet.
- Enhanced the "Not Found" page for better mobile view.
- Improved error handling and passthrough in faucet actions.
- Fixed the issue of showing a chain banner when no chain is detected.
- Reduced the width of the wallet network dropdown to the minimum content width.
- Cleaned up the faucet by removing unused functions.
- Remove $ Symbol from SENT Symbol
- Fixed gradient styles to ensure correct colour usage.
- Updated test data generation to include new node variants.
- Improved and cleaned up module styles.
- Made basic style adjustments and environment fixes for the staking page.
- General cleanup of staking modules.
- Added necessary containers and height logic to the stakes page.
- Improved and cleaned up the mobile landing page.
- Added an environment flag to the next dev script.

2024-07-03 06:44 UTC, yougotwill requested changes
Nice job dude!

2024-07-03 06:44 UTC, yougotwill commented on apps/staking/app/faucet/actions.ts
> +      abi: SENTAbi,
Cool

2024-07-03 06:44 UTC, yougotwill commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +  return (
Do we still want to if there are no nodes? It would render an empty div. We could return null above?

```tsx
if (!data.nodes.length) {
  return null;
}
```

2024-07-03 06:44 UTC, yougotwill commented on apps/staking/components/StakedNodeCard.tsx
> +  ({ className, contributors, showEmptySlots, ...props }, ref) => {
Cool thanks for explaining clearly

2024-07-03 06:44 UTC, yougotwill commented on apps/staking/lib/sent-staking-server-client.ts
> +async function request<T>(options: SSBRequestOptions): Promise<SSBResponse<T>> {
Might be good to have client and server in the type names in future then? Resolving for now.

2024-07-03 06:44 UTC, yougotwill commented on packages/wallet/hooks/wallet-hooks.tsx
> +      if (error instanceof Error) {
Cool

2024-07-03 06:44 UTC, yougotwill commented on packages/wallet/hooks/wallet-hooks.tsx
> +        setError(error.message);
👍

2024-07-03 06:47 UTC, Aerilym commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +  return (
One step ahead of you, PR #9 has this change:
```tsx
<ModuleGridContent className="h-full md:overflow-y-auto">
      {isLoading ? (
        <Loading />
      ) : nodes && nodes.length > 0 ? (
        nodes.map((node) => (
          <StakedNodeCard
            key={node.service_node_pubkey}
            node={parseSessionNodeData(node) as StakedNode}
          />
        ))
      ) : (
        <NoNodes />
      )}
    </ModuleGridContent>
```

2024-07-03 06:48 UTC, yougotwill commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +  return (
Noice

2024-07-03 06:51 UTC, yougotwill commented on packages/wallet/components/WalletNetworkDropdown.tsx
> +export type WalletNetworkButtonProps = ButtonVariantProps & {
I think having the ability to customize some aspects (such as color) but default to `session-green` would be useful in future. But we aren't near that at all so for now don't worry about it.

2024-07-03 06:53 UTC, yougotwill commented on packages/ui/components/ui/dropdown-menu.tsx
> +        <Check className="h-4 w-4" />
Sorry my english failed me here. I believe I meant using `fill-current` tailwind class on the check svg? So it inherits the color from the parent span.

2024-07-03 06:55 UTC, yougotwill commented on apps/staking/testing/data-test-ids.tsx
> +export enum ButtonDataTestId {
Very very nice 👑

2024-07-03 06:55 UTC, yougotwill commented on apps/staking/package.json
> +    "viem": "2.13.7"
Cool

2024-07-03 06:56 UTC, yougotwill commented on apps/staking/lib/locale-client.ts
> +export const useLocale = (): Locale => nextIntlUseLocale() as Locale;
* surprised pikachu * Cool cool

2024-07-03 06:56 UTC, yougotwill commented on apps/staking/components/WalletModalButtonWithLocales.tsx
> +export function WalletModalButtonWithLocales() {
I agree given the context

2024-07-03 06:57 UTC, yougotwill commented on apps/staking/components/StakedNodeCard.tsx
> +                <ContributorIcon key={index} className="fill-text-primary h-4" />
Interesting will see the workaround later. Resolved

2024-07-03 06:58 UTC, yougotwill commented on apps/staking/components/Header.tsx
> +          href="/faucet"
Cool cool

2024-07-03 06:59 UTC, yougotwill commented on apps/staking/app/faucet/actions.ts
> +const minEthBalance = 0.001;
Okay cool.

2024-07-22 01:05 UTC, yougotwill approved these changes
LGTM 🚢

2024-07-22 01:05 UTC, merged