Exit and liquidation feature
oxen-io/websites pull request #44
Opened 2024-09-10 08:43 UTC by Aerilym

2024-09-10 15:08 UTC, yougotwill requested changes
- I can't build the staking app because it's complaining about the `@ts-expect-error` in `tooltip.tsx`. I replaced it with a `@ts-ignore` and it builds
- sent-staking-js/test.ts is missing `contract_id`
- When I went to `/stake` on localhost:3000 I get the following error

```tsx
RangeError: 730.511935977951 can't be converted to BigInt because it isn't an integer
Source

../packages/sent-staking-js/test.ts (37:13) @ BigInt

  35 |   return {
  36 |     address: generateWalletAddress(),
> 37 |     amount: BigInt(Math.random() * 1000),
     |             ^
  38 |     reserved: BigInt(Math.random() * 1000),
  39 |     locked_contributions: [],
  40 |   };
```

2024-09-10 15:08 UTC, yougotwill commented on apps/staking/components/StakedNode/NodeRequestExitButton.tsx
> +  } = useInitiateRemoveBLSPublicKey({
This hook has gotten quite big damn.

2024-09-10 15:08 UTC, yougotwill commented on apps/staking/components/StakedNode/NodeRequestExitButton.tsx
> +function QueryStatusInformation({
Yeah definitely should split these components up a bit

2024-09-10 22:32 UTC, Aerilym commented on apps/staking/app/mystakes/modules/ClaimTokensModule.tsx
> +  const claimRewardsArgs = useMemo(
I'm not entirely convinced its needed, but I had to make this change for the new contract call as part of exiting, it probably does nothing in this case but best case scenario its memoised and not triggering extra re-renders, worst case, it does nothing.

2024-09-10 22:35 UTC, Aerilym commented on apps/staking/locales/en.json
> +      "requestingExitDescription": "Time left until the node is available for exit. Return {relative_time} ({date}) to exit the node.",
yeah `{date}` is, the dynamic variable `{date}` is just being wrapped in parenthesis to make the string look like:
`Time left until the node is available for exit. Return in 14 days (Wednesday, 11 September 2024 at 11:23:52pm GMT+10) to exit the node.`

2024-09-10 22:36 UTC, Aerilym commented on apps/staking/components/StakedNode/NodeRequestExitButton.tsx
> +function RequestNodeExitContractWriteDialog({ node }: { node: StakedNode }) {
Yeah im looking to make a contract write dialog generic as this has quite similar code to 2 other places already

2024-09-10 22:36 UTC, Aerilym commented on apps/staking/components/StakedNode/NodeRequestExitButton.tsx
> +function QueryStatusInformation({
Yeah for sure, see above

2024-09-10 22:39 UTC, Aerilym commented on packages/contracts/hooks/ServiceNodeRewards.tsx
> +  const defaultArgs = useMemo(() => [BigInt(contractId ?? 0)] as [bigint], [contractId]);
It has to be `[bigint]` as that is the smart contract arg, as in, it is a literal single item array where that one item is a `bigint`. This isn't be the same as `Array<bigint>` which is a 0-∞ size array where each item is a `bigint`.

2024-09-10 22:44 UTC, Aerilym commented on apps/staking/components/StakedNodeCard.tsx
> +    node.deregistrationDate
`'deregistrationDate' in node` checks that `deregistrationDate` is a property on the `node` object, as in it checks if it is declared/exists. This then allows us to do `node.deregistrationDate` as the previous check was true so we know `deregistrationDate` is declared and we can now check for its thuthyness

2024-09-10 22:48 UTC, Aerilym commented on packages/ui/components/ui/tooltip.tsx
>  import { useDebounce } from '@uidotdev/usehooks';
damn, ok fixed

2024-09-10 22:56 UTC, Aerilym commented
> * I can't build the staking app because it's complaining about the `@ts-expect-error` in `tooltip.tsx`. I replaced it with a `@ts-ignore` and it builds
> 
>     * sent-staking-js/test.ts is missing `contract_id`
> 
>     * When I went to `/stake` on localhost:3000 I get the following error
> 
> 
> ```tsx
> RangeError: 730.511935977951 can't be converted to BigInt because it isn't an integer
> Source
> 
> ../packages/sent-staking-js/test.ts (37:13) @ BigInt
> 
>   35 |   return {
>   36 |     address: generateWalletAddress(),
> > 37 |     amount: BigInt(Math.random() * 1000),
>      |             ^
>   38 |     reserved: BigInt(Math.random() * 1000),
>   39 |     locked_contributions: [],
>   40 |   };
> ```

Changes made. Ive also fixed those broken tests for you :)

2024-09-11 03:53 UTC, yougotwill approved these changes
LGTM 🚢

2024-09-11 03:53 UTC, yougotwill commented on packages/contracts/hooks/ServiceNodeRewards.tsx
> +  const defaultArgs = useMemo(() => [BigInt(contractId ?? 0)] as [bigint], [contractId]);
I see. My mistake sorry. All good 👍

2024-09-11 03:53 UTC, yougotwill commented on apps/staking/components/StakedNodeCard.tsx
> +    node.deregistrationDate
Cool

2024-09-11 03:54 UTC, merged