Staking card backend generation & Fixes
oxen-io/websites pull request #53
Opened 2024-09-25 01:42 UTC by Aerilym

2024-09-25 13:08 UTC, yougotwill commented on apps/staking/components/DevSheet.tsx
> +    });
Very nice 👌

2024-09-25 13:09 UTC, yougotwill commented on apps/staking/components/DevSheet.tsx
> +}
Yeah all this new code should probably be in a separate file. If you still want to keep it with the dev sheet. Maybe setup a feature folder.

2024-09-25 13:09 UTC, yougotwill commented on apps/staking/app/stake/[nodeId]/NodeStaking.tsx
> +      {/*</ActionModuleRow>*/}
Is this staying uncommented?

2024-09-25 23:32 UTC, Aerilym commented on apps/staking/lib/constants.ts
> +  SOON_TIME = 120_000,
Yeah it better fragments the number so you can read it easier

2024-09-25 23:33 UTC, Aerilym commented on apps/staking/components/DevSheet.tsx
> +}
Yeah makes sense. Will be splitting a bunch of files soon

2024-09-25 23:35 UTC, Aerilym commented on apps/staking/locales/en.json
> +      "exitTimerNotificationNow": "Exit now to avoid penalty.",
For if `Date.now() > exitTime + gracePeriod`

2024-09-25 23:38 UTC, Aerilym commented on packages/contracts/hooks/SENT.tsx
> +  formatSENTBigInt(value ? BigInt(value) : null, decimals, hideSymbol);
We can only create a bigint if the value is a number or string (here value can be number ot null). If its not null we pass it to the function and if its null we pass null to the function. See the function it calls: formatSENTBigInt

2024-09-25 23:43 UTC, Aerilym commented on apps/staking/components/StakedNodeCard.tsx
> +  stake.exited || ('contract_id' in stake && stake.contract_id === null);
Its one of the many edge cases. If a node has exited the smart contract and the network hasn't confirmed the event yet then the contract_id is null. BUT this should not happen as the node info should be stored in the database and the backend should use that data, which includes the contract_id. So its a technically possible edge case but not likley to happen as long as the backend is doing its job well. BUT if people host their own backend there is no guarentee the database has the contract_id for the node.

2024-09-25 23:46 UTC, Aerilym commented on apps/staking/components/StakedNodeCard.tsx
>  };
Yeah i thought about it, will do when i have more time

2024-09-25 23:46 UTC, Aerilym commented on apps/staking/components/StakedNodeCard.tsx
> +  );
probably can at some point but it works now so i dont want to spend too much time on it

2024-09-25 23:47 UTC, Aerilym commented on apps/staking/components/StakedNodeCard.tsx
> +  const relativeTime = (!isDeregistrationSoon ? timeString : soonString) ?? notFoundString;
fixed

2024-09-25 23:57 UTC, Aerilym commented on apps/staking/components/StakedNodeCard.tsx
> +      ? blockTime.getDateOfBlock(currentBlock + earnedDowntimeBlocks)
I disagree, `getDateOfBlock` should return a date, in these usecases we want a date only if the event exists and is not `0`, I think retuning null inside `getDateOfBlock` would obscure this logic. Making this change would also mean `getDateOfBlock` would return the Date object of unix 0, which is not what we want here

2024-09-26 00:01 UTC, Aerilym commented on packages/sent-staking-js/test.ts
> +    amount: Math.round(Math.random() * 1000),
to match the type which is number again lol

2024-09-26 00:03 UTC, Aerilym commented on packages/sent-staking-js/test.ts
> +    earned_downtime_blocks: 20,
its a random number that came to me in a dream.

2024-09-26 00:04 UTC, Aerilym commented on packages/sent-staking-js/test.ts
> +    earned_downtime_blocks: 20,
it is actually meaningless, I just needed a number between 1 and 60

2024-09-26 00:10 UTC, Aerilym commented on packages/sent-staking-js/test.ts
> +    earned_downtime_blocks: 20,
Also i dont want to spend any time in this file as its basically useless at this point with all the backend changes, im honestly surprised the mock data that is generated still kinda works with this minor fixes i did. When i focus on qa and testing logic I'll refactor this nightmare

2024-09-26 06:56 UTC, yougotwill requested changes

2024-09-26 06:56 UTC, yougotwill commented on apps/staking/components/StakedNodeCard.tsx
> +      ? blockTime.getDateOfBlock(currentBlock + earnedDowntimeBlocks)
I see your point. Let's leave it. Resolving.

2024-09-26 06:56 UTC, yougotwill commented on apps/staking/locales/en.json
> +      "exitTimerNotificationNow": "Exit now to avoid penalty.",
I understand what it is for. Sorry should have been specific. I was suggesting an update to string itself. "avoid a penality" instead of "avoid penalty"

2024-09-26 06:56 UTC, yougotwill commented on packages/contracts/hooks/SENT.tsx
> +  formatSENTBigInt(value ? BigInt(value) : null, decimals, hideSymbol);
Cool, suprised bit int doesn't just resolve it to zero or something. All god

2024-09-26 06:56 UTC, yougotwill commented on packages/sent-staking-js/test.ts
> +    earned_downtime_blocks: 20,
Cool. Maybe just add a top level comment saying this file will be removed or replace in future please

2024-09-26 07:02 UTC, Aerilym commented on apps/staking/locales/en.json
> +      "exitTimerNotificationNow": "Exit now to avoid penalty.",
Ah right, well its like this is prod already, I do plan on doing a strings review with marketing at some point. But I dont want to make this change right now, everyone is happy with it atm.

2024-09-26 07:05 UTC, yougotwill approved these changes
LGTM 🚢

2024-09-26 07:08 UTC, merged