Sanity cms
oxen-io/websites pull request #57
Opened 2024-09-30 06:31 UTC by Aerilym

2024-10-01 07:29 UTC, yougotwill requested changes
Great work man! Couple of comments

2024-10-01 07:29 UTC, yougotwill commented on packages/sanity-cms/components/SanityStudioSSRPage.tsx
> +export const dynamic = 'force-static';
What does this do? Can you docstring it please?🙏

2024-10-01 07:29 UTC, yougotwill commented on packages/sanity-cms/api/revalidate.ts
> +      revalidateTag(body._type);
Yeah once I'm back you are going to have to teach me this stuff. Impressive but also a bit beyond my current knowledge

2024-10-01 23:15 UTC, Aerilym commented on packages/util-js/env.ts
> + * set, it defaults to fetches it from the NEXT_PUBLIC_ENV_FLAG environment variable.
Yeah will have to work out a better solution, the only env variables client-side next can see are ones prefixed with `NEXT_PUBLIC_`. When we use this on desktop we can decide on what to use cross-environment.

2024-10-01 23:16 UTC, Aerilym commented on packages/util-js/env.ts
> +    console.warn(`Invalid environment: ${environment}`);
Just a warning, have updated to say it defaults to `dev` now

2024-10-01 23:22 UTC, Aerilym commented on packages/sanity-cms/lib/fetch.ts
> + * workers versions).
hahaha i may have been a little fed up at that point. but im not wrong. :)

2024-10-01 23:24 UTC, Aerilym commented on packages/sanity-cms/queries/getPages.ts
> +  const [err, result] = await client.nextFetch<QUERY_GET_LIST_OF_PAGES_RETURN_TYPE>({
It is, nextFetch uses it under the hood:
```ts

export const sanityFetchGeneric = async <R = unknown>({
//...
}: SanityFetchGenericOptions) =>
  safeTry<R>(
    (async () => {
      //...
    })()
  );
```

2024-10-01 23:30 UTC, Aerilym commented on packages/sanity-cms/lib/preview.ts
> +function getPreviewUrl(route: RouteSchemaType) {
deleted :)

2024-10-01 23:31 UTC, Aerilym commented on packages/sanity-types/README.md
> +export type SchemaFieldsType<Fields extends SchemaFields<CustomFieldTypeMap>> = GenericSchemaType<
I'm not sure what you mean? I show the type being used to create a schema type?

2024-10-01 23:33 UTC, Aerilym commented on packages/util-js/README.md
> +This package is a js utility library for common functions.
I mean it's written in ts but all the functionality is transpiled to js so it is a js utility library. imo something is only a ts library if its explicitly for ts, not js. eg: sanity-types vs sent-staking-js

2024-10-01 23:34 UTC, Aerilym commented on packages/sanity-cms/api/revalidate.ts
> +      revalidateTag(body._type);
haha sounds good, theres a lot of next magic going on

2024-10-01 23:37 UTC, Aerilym commented on packages/sanity-cms/components/SanityStudioSSRPage.tsx
> +export const dynamic = 'force-static';
added

2024-10-01 23:41 UTC, Aerilym commented on packages/sanity-cms/schemas/fields/basic/seo.ts
> +    metaTitle: 'seo',
This is using the [sanity-seo-plugin](https://www.sanity.io/plugins/sanity-seo-plugin), the `seoMetaFields` type gives you:
```ts
export type SeoType = {
  _type?: 'seo';
  nofollowAttributes?: boolean;
  metaDescription?: string;
  additionalMetaTags?: MetaTagType[];
  metaTitle?: string;
  seoKeywords?: string[];
  openGraph?: OpenGraphType;
  twitter?: Twitter;
};

export type MetaTagType = {
  _type: 'metaTag';
  metaAttributes?: MetaAttributeType[];
};

export type MetaAttributeType = {
  _type: 'metaAttribute';
  attributeKey?: string;
  attributeType?: string;
  attributeValueString?: string;
  attributeValueImage?: CustomImageType;
};

export type OpenGraphType = {
  _type: 'openGraph';
  title: string;
  url?: string;
  siteName?: string;
  description: string;
  image: CustomImageType;
};

export type Twitter = {
  _type: 'twitter';
  handle?: string;
  creator?: string;
  site?: string;
  cardType?: string;
};
```

2024-10-01 23:42 UTC, Aerilym commented on packages/sanity-cms/schemas/fields/basic/seo.ts
> +    metaTitle: 'seo',
I'll add the schema type to this PR because i finished it just now

2024-10-01 23:48 UTC, Aerilym commented on packages/util-js/try.ts
> +export async function safeTry<T, E = Error>(promise: Promise<T>): Promise<[null, T] | [E, null]> {
I decided to give it a go, would be incredible for the general state management and integrity problem with decentralized apps, plus I think it has a lot of potential for general js stability improvements. It's a basic implementation of the sage 0 safe assignment operator
TypeScript proposal:
- https://github.com/arthurfiorette/proposal-safe-assignment-operator
- https://arthur.run/proposal-safe-assignment-operator/

2024-10-01 23:52 UTC, Aerilym commented on packages/sanity-cms/schemas/fields/basic/seo.ts
> +    metaTitle: 'seo',
Added

2024-10-01 23:52 UTC, Aerilym commented on packages/sanity-cms/lib/util.ts
> +    logger.error(`Error getting draft mode`, error);
I hope so, still implementing proper draft mode in nextjs, will see soon

2024-10-03 04:54 UTC, yougotwill approved these changes
LGTM 🚢

2024-10-03 04:54 UTC, yougotwill commented on packages/sanity-cms/queries/getPages.ts
> +  const [err, result] = await client.nextFetch<QUERY_GET_LIST_OF_PAGES_RETURN_TYPE>({
Nice I missed that.

2024-10-03 04:54 UTC, yougotwill commented on packages/sanity-types/README.md
> +export type SchemaFieldsType<Fields extends SchemaFields<CustomFieldTypeMap>> = GenericSchemaType<
So you did. I must have read this incorrectly on first pass. Resolving

2024-10-03 04:54 UTC, yougotwill commented on packages/util-js/README.md
> +This package is a js utility library for common functions.
You make a good point

2024-10-03 04:54 UTC, yougotwill commented on packages/util-js/env.ts
> + * set, it defaults to fetches it from the NEXT_PUBLIC_ENV_FLAG environment variable.
You could probably have an optional flag prefix variable or something. All good resolving.

2024-10-03 04:54 UTC, yougotwill commented on packages/util-js/try.ts
> +export async function safeTry<T, E = Error>(promise: Promise<T>): Promise<[null, T] | [E, null]> {
Nice

2024-10-03 04:54 UTC, yougotwill commented on packages/sanity-cms/schemas/fields/basic/seo.ts
> +    metaTitle: 'seo',
Nice thanks for that 🙏

2024-10-03 05:01 UTC, merged