Session technology foundation site baseline
oxen-io/websites pull request #60
Opened 2024-10-07 01:05 UTC by Aerilym

2024-10-08 13:10 UTC, yougotwill requested changes

2024-10-09 01:57 UTC, Aerilym reviewed
Changes made

2024-10-09 01:57 UTC, Aerilym commented on packages/sanity-cms/tailwind.config.ts
> +export { default } from '@session/ui/taiwind';
Fixed

2024-10-09 01:57 UTC, Aerilym commented on packages/sanity-types/index.ts
> +  date: string;
The https://www.sanity.io/docs/date-type date type is string as its `yyyy-mm-dd` :smile:

2024-10-09 01:57 UTC, Aerilym commented on packages/ui/components/NavLink.tsx
>  /** TODO: This was copied from the staking portal, investigate if we can turn it into a shared library */
Yeah because the staking portal isn't using it

2024-10-09 01:57 UTC, Aerilym commented on packages/ui/components/Typography.tsx
> +export default function Typography({ variant, className, children }: TypographyProps) {
line-height is determined by tailwind text size https://tailwindcss.com/docs/font-size
So this is fine

2024-10-09 01:57 UTC, Aerilym commented on packages/ui/styles/global.css
> +    --session-green-dark: #00aa59;
Just a darker session green, might scrap it later

2024-10-09 01:57 UTC, Aerilym commented on packages/util-logger/tests/index.spec.ts
> +  // TODO: re-enable once we fix the logger
separately its a mess :melting_face:

2024-10-09 01:57 UTC, Aerilym commented on turbo.json
> +        "NEXT_PUBLIC_SANITY_PROJECT_ID",
nope

2024-10-09 01:58 UTC, Aerilym commented on apps/foundation/public/images/logo.svg
> +<svg width="102" height="31" fill="none" xmlns="http://www.w3.org/2000/svg"
Yes i built this by hand and optimised it :)

2024-10-09 02:18 UTC, Aerilym commented on apps/foundation/public/favicon.svg
> +<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.dev/svgjs" width="1000" height="1000"><g clip-path="url(#SvgjsClipPath1257)"
Kinda, it was a tool that added the circle, ive edited it now

2024-10-09 02:18 UTC, Aerilym commented on packages/sanity-cms/schemas/fields/generated/copy.tsx
> +              B<sup>+</sup>
That creates the icon.

Big bold is text that is big and bold

2024-10-09 02:20 UTC, Aerilym commented on apps/foundation/lib/env.ts
> +}
Yeah its nice because it'll mean typescript knows these variables are defined when used, but if they are missing and error is thrown, perfecto

2024-10-09 02:20 UTC, Aerilym commented on apps/foundation/.env.local.template
> +SANITY_REVALIDATE_SECRET=
no need for write token

2024-10-09 08:21 UTC, yougotwill reviewed
Couple missed comments we need to resolve

2024-10-09 08:21 UTC, yougotwill commented on apps/foundation/components/RouterResetInput.tsx
> +export default function RouterResetInput({ id, className }: RouterResetInputProps) {
Ah I see interesting solution. I think I did it slightly different on the token site. Can't quite remember my approach.

2024-10-09 08:21 UTC, yougotwill commented on packages/ui/components/Typography.tsx
> +export default function Typography({ variant, className, children }: TypographyProps) {
Oh true, totally forgot that. Resolving 🙏

2024-10-09 08:21 UTC, yougotwill commented on packages/sanity-cms/schemas/fields/generated/copy.tsx
> +              B<sup>+</sup>
Oh right it's the icon within sanity studio. I was think it was rendering on the site and thought you have some weird regex rendering hack going on 😂

2024-10-09 08:21 UTC, yougotwill commented on packages/sanity-cms/queries/getContent.ts
> +  const content = result[0];
@Aerilym This comment seems to be have missed

2024-10-09 08:21 UTC, yougotwill commented on packages/sanity-cms/queries/getAuthor.ts
> +  const [err, result] = await client.nextFetch<QUERY_GET_AUTHORS_RETURN_TYPE>({
@Aerilym missed

2024-10-09 08:21 UTC, yougotwill commented on packages/sanity-cms/components/SanityTile.tsx
> +      <span className="ms-2 text-xs font-light md:text-sm">{value.description ?? ' '}</span>
Goddamit. I meant using figure and caption here instead of div and span.

2024-10-09 08:21 UTC, yougotwill commented on apps/foundation/next.config.mjs
> +    config.externals.push('pino-pretty', 'lokijs', 'encoding');
Ah I see cool. resolving

2024-10-09 23:00 UTC, Aerilym commented on packages/sanity-cms/components/SanityTile.tsx
> +      <span className="ms-2 text-xs font-light md:text-sm">{value.description ?? ' '}</span>
no can do, the <figure> element is hot garbage :)

wont work properly for multiple bits of text. but also its not appropriate here because the text is not a caption of the image, the image is just design fluf, which is why the images here also dont have alt tags

2024-10-09 23:24 UTC, Aerilym commented on packages/sanity-cms/queries/getContent.ts
> +  const content = result[0];
Ids are globally unique, so only ever between 0 and 1 result. just a javascript being a pain and not having strictly defined array lengths

2024-10-09 23:25 UTC, Aerilym commented on packages/sanity-cms/queries/getAuthor.ts
> +  const [err, result] = await client.nextFetch<QUERY_GET_AUTHORS_RETURN_TYPE>({
yeah the query is wrong, we dont use it tho, will fix it now

2024-10-10 04:12 UTC, yougotwill commented on packages/sanity-cms/queries/getContent.ts
> +  const content = result[0];
Cool

2024-10-10 04:30 UTC, yougotwill approved these changes
LGTM 🚢

2024-10-10 04:32 UTC, merged