Open Nodes
oxen-io/websites pull request #9
Opened 2024-06-25 01:37 UTC by Aerilym

2024-07-01 01:58 UTC, Bilb commented on package.json
> +  }
shouldn't this be in devDeps too?

2024-07-01 01:58 UTC, Bilb commented on packages/contracts/tests/chains.spec.ts
> +    expect(Object.keys(CHAIN)).toEqual(['MAINNET', 'TESTNET', 'ETHEREUM']);
I think we had a chat with Will about this, but I think, since es6, Object.Keys return is defined, but wasn't before.
Maybe this should be a sorted, both sides before doing a toEqual?

2024-07-01 01:58 UTC, Bilb commented on packages/contracts/tests/chains.spec.ts
> +    expect(isChain('potatochain')).toBe(false);
:potato:

2024-07-01 01:58 UTC, Bilb commented on packages/wallet/hooks/wallet-hooks.tsx
> +    //find the key where the value.id is equal to chainId
```suggestion
    // find the key where the value.id is equal to chainId
```

2024-07-01 01:58 UTC, Bilb commented on packages/util/tests/build.spec.ts
> +    const commitHash = execSync('git rev-parse HEAD').toString().trim();
idk if that works on windows, but I guess we don't really need to care for now.

2024-07-01 01:58 UTC, Bilb commented on packages/util/tests/build.spec.ts
> +    const commitHash = execSync('git rev-parse HEAD').toString().trim();
same comment

2024-07-01 02:17 UTC, Aerilym commented on package.json
> +  }
Ah yeah it should be, good catch

2024-07-01 02:17 UTC, Aerilym commented on packages/util/tests/build.spec.ts
> +    const commitHash = execSync('git rev-parse HEAD').toString().trim();
Hmm yeah good point, I guess the idea is the build info is only relevant on release and dev builds which are all done on linux and in CI. Would be curious to know if this fails on windows tho.

2024-07-01 02:17 UTC, Aerilym commented on packages/contracts/tests/chains.spec.ts
> +    expect(Object.keys(CHAIN)).toEqual(['MAINNET', 'TESTNET', 'ETHEREUM']);
I see, I've removed the order requirement as its not important for this const, instead I'm now checking that the keys array contains the required value, this works the same as ignoring the order.

2024-07-04 03:41 UTC, yougotwill requested changes
Nice work dude!

2024-07-04 03:41 UTC, yougotwill commented on apps/staking/app/mystakes/modules/TotalRewardsModule.tsx
> +  // const toastDictionary = useTranslations('modules.toast');
Cleanup?

2024-07-04 03:41 UTC, yougotwill commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +  const nodes = useMemo(() => {
Can't type the return in the function signature with Array<ServiceNode>?

2024-07-04 03:41 UTC, yougotwill commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +      ) : nodes && nodes.length > 0 ? (
Learned this from Audric but you can just go `nodes && && nodes.length` since 0 is falsy

2024-07-04 03:41 UTC, yougotwill commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +          <span className="hidden sm:block">{dictionary('showHiddenText')}</span> <Switch />
block md:hidden?

2024-07-04 03:41 UTC, yougotwill commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
>      ...(node.decomm_blocks_remaining
```suggestion
    awaitingLiquidation: node.awaiting_liquidation ? true : undefined,
```

Possibly?

2024-07-04 03:41 UTC, yougotwill commented on apps/staking/app/mystakes/modules/BalanceModule.tsx
> +          fontSize: `clamp(32px, min(${(formattedTotalStakedAmount?.length ?? 0) / 2}ch, 8vw), 100px)`,
🧙‍♂️

2024-07-19 05:07 UTC, Aerilym commented on packages/ui/components/ui/button.tsx
>      const Comp = asChild ? Slot : 'button';
its ok, but we need to resolve this font issue someday

2024-07-19 05:09 UTC, Aerilym commented on packages/ui/components/CopyToClipboardButton.tsx
> +        <ClipboardIcon className="fill-session-white h-5 w-5" />
not yet but if we do we can build it :)

2024-07-19 05:10 UTC, Aerilym commented on apps/staking/providers/feature-flag-provider.tsx
> +type FeatureFlags = Record<FEATURE_FLAG, boolean>;
Done

2024-07-19 05:11 UTC, Aerilym commented on apps/staking/lib/locale-defaults.tsx
> +  'text-extralight': text('font-extralight'),
Yeah it makes more sense because its not a style but an element, so its clear its just text with a specific style

2024-07-19 05:45 UTC, Aerilym commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +          <span className="hidden sm:block">{dictionary('showHiddenText')}</span> <Switch />
we only want the text when big

2024-07-19 05:46 UTC, Aerilym commented on apps/staking/components/OpenNodeCard.tsx
> +      className="flex flex-col items-center justify-between gap-2 align-middle sm:flex-row md:gap-10"
this is a lot more complicated than mobile vs desktop, we've had to do some complex logic to get all this data to fit on all screens :)

2024-07-19 05:47 UTC, Aerilym commented on apps/staking/app/stake/OpenNodes.tsx
> +      return [] as Array<OpenNode>;
what was this related to? its been lost since all the changes

2024-07-19 05:52 UTC, Aerilym commented on packages/sent-staking-js/test.ts
> +  maxContributors,
Will be reworking the test code generators as they dont work great anymore

2024-07-19 06:02 UTC, Aerilym commented on packages/wallet/hooks/wallet-hooks.tsx
> +export const useToggleWalletModal = (): ReturnType<typeof useWeb3Modal> => {
yeah toggle wallet?

2024-07-19 06:03 UTC, Aerilym commented on packages/wallet/hooks/wallet-hooks.tsx
> +export const useToggleWalletModal = (): ReturnType<typeof useWeb3Modal> => {
haha but yeah it toggles the wallet info/modal visibility

2024-07-19 06:04 UTC, Aerilym commented on packages/util/tests/string.spec.ts
> +// #region - collapseString
Fixed

2024-07-19 06:04 UTC, Aerilym commented on packages/util/build.ts
> + * @returns An object containing the build information.
Added to jira

2024-07-19 06:05 UTC, Aerilym commented on packages/testing/tsconfig.json
> +  "include": ["./*", "tests/**.ts", "jest.config.js", "config/jest.**.config.js"],
fixed

2024-07-19 06:05 UTC, Aerilym commented on apps/staking/locales/en.json
> +    "title": "Stake <text-semibold>{tokenSymbol}</text-semibold> Earn Rewards",
discussed

2024-07-19 06:05 UTC, Aerilym commented on apps/staking/lib/constants.ts
> +  LEARN_MORE_UNCLAIMED_REWARDS = 'https://docs.getsession.org/',
Done

2024-07-19 06:07 UTC, Aerilym commented on apps/staking/components/OpenNodeCard.tsx
> +        <div className="flex w-full cursor-pointer items-baseline gap-3 text-center align-middle sm:text-start">
not sure what u mean

2024-07-19 06:08 UTC, Aerilym commented on apps/staking/app/stake/node/[nodeId]/NodeStaking.tsx
> +    <span>Node not found</span>
replaced

2024-07-19 06:08 UTC, Aerilym commented on apps/staking/app/mystakes/modules/TotalRewardsModule.tsx
> +  // const toastDictionary = useTranslations('modules.toast');
will need in future feature

2024-07-19 06:09 UTC, Aerilym commented on apps/staking/app/mystakes/modules/StakedNodesModule.tsx
> +  const nodes = useMemo(() => {
sorry?

2024-07-22 00:56 UTC, yougotwill commented on apps/staking/app/stake/node/[nodeId]/NodeStaking.tsx
> +    <span>Node not found</span>
"Node not found" is still not localisation

2024-07-22 01:06 UTC, yougotwill approved these changes
LGTM 🚢

2024-07-22 01:07 UTC, merged